### Get from localhost all the books
GET http://localhost:3000/books
### Get from localhost 1 book
GET http://localhost:3000/books/65b436473d8e139541fe1c9e

### Create book
POST http://localhost:3000/books HTTP/1.1
content-type: application/json

{
    "title": "The Catcher in the Rye",
    "author": "J.D. Salinger",
    "genre": "Coming-of-Age",
    "publishedYear": 1951,
    "pages": 224,
    "protagonist": "Holden Caulfield",
    "themes": ["Alienation", "Identity", "Innocence"],
    "setting": "New York City"
}

### Update book
PUT http://localhost:3000/books/65b436473d8e139541fe1c95 HTTP/1.1
content-type: application/json

{
    "title": "Harry Potter and the Sorcerer's Stone",
    "author": "J.K. Rowling",
    "genre": "Fantasy",
    "publishedYear": 1997,
    "pages": 309,
    "protagonist": "Harry Potter",
    "themes": ["Friendship", "Courage", "Good vs. Evil"],
    "setting": "Hogwarts School of Witchcraft and Wizardry"
}

### Delete book 
DELETE http://localhost:3000/books/65b436473d8e139541fe1c95 HTTP/1.1




### Get from localhost all the clients
GET http://localhost:3000/clients
### Get from localhost 1 client
GET http://localhost:3000/clients/65b5ce1ea03c6f38c4e6d3ce

### Create client
POST http://localhost:clients/clients HTTP/1.1
content-type: application/json

{
    "name": "David Wilson",
    "email": "david@example.com",
    "phone": "555-7890",
    "address": "654 Maple St, Rural, Country"
}

### Update client
PUT http://localhost:3000/clients/65b436473d8e139541fe1c95 HTTP/1.1
content-type: application/json

{
    "name": "Sophia Lee",
    "email": "sophia@example.com",
    "phone": "555-2345",
    "address": "321 Birch St, Countryside, Country"
}

### Delete client 
DELETE http://localhost:3000/clients/65b436473d8e139541fe1c95 HTTP/1.1